@url = http://localhost:4000/api
//@url = http://crypto-bank-1612785.herokuapp.com/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZWU4YTZjOGVjNTdhNjI2YWM1ZGUyNTYiLCJpYXQiOjE1OTIzMDU0MDAsImV4cCI6MTU5MjkxMDIwMH0.dJJAF4e4rigVkgSBDDzWPOYNBy4rE2Rwr1yTojQJcAY

### Đăng ký tài khoản ngân hàng
POST {{url}}/auth/register
Content-Type: application/json

{
    "username": "dangthanhtuan",
    "password": "123456",
    "full_name" : "Đặng Thanh Tuấn"
}

###
POST {{url}}/auth/login
Content-Type: application/json

{
    "username": "dangthanhtuan",
    "password": "123456"
}

###

GET {{url}}/users/123456789
x-access-token: JWT {{token}}


###

GET {{url}}/users/me
x-access-token: JWT {{token}}

###

POST {{url}}/transactions
Content-Type: application/json
x-access-token: JWT {{token}}

{
    "amount": 50000,
    "receiver": {
        "account_number": "123456789",
        "full_name": "Nguyễn Sĩ Văn"
    },
    "note": "Note is not required"
}