@url = http://localhost:4000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZWUwOTY3YTM5OTQzMzBiMTA5ODM1YWUiLCJpYXQiOjE1OTIwNjQ1NTEsImV4cCI6MTU5MjY2OTM1MX0.ttx5m7rMMuu8iU50hGLWae9haXbcXi7ITh7G4_xZh2w

### Đăng ký tài khoản ngân hàng
POST {{url}}/auth/register
Content-Type: application/json

{
    "username": "dangthanhtuan",
    "password": "123456",
    "full_name" : "Đặng Thanh Tuấn"
}

###
POST {{url}}/auth/login
Content-Type: application/json

{
    "username": "dangthanhtuan",
    "password": "123456"
}

###

GET {{url}}/users/dangthanhtuan
x-access-token: JWT {{token}}


###

GET {{url}}/users/me
x-access-token: JWT {{token}}