@url = http://localhost:4000/api
//@url = http://crypto-bank-1612785.herokuapp.com/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZWUwOTY3YTM5OTQzMzBiMTA5ODM1YWUiLCJpYXQiOjE1OTIyOTY3OTksImV4cCI6MTU5MjkwMTU5OX0.73mOO8be3zGII21iz7zEp3R2j7_9Nyas_K7_wkdyXMk

### Đăng ký tài khoản ngân hàng
POST {{url}}/auth/register
Content-Type: application/json

{
    "username": "dangthanhtuan",
    "password": "123456",
    "full_name" : "Đặng Thanh Tuấn"
}

###
POST {{url}}/auth/login
Content-Type: application/json

{
    "username": "dangthanhtuan",
    "password": "123456"
}

###

GET {{url}}/users/0000473924959
x-access-token: JWT {{token}}


###

GET {{url}}/users/me
x-access-token: JWT {{token}}